# This file was sourced from [Mipha](https://github.com/AbstractUmbra/Mipha/).

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

[tool.ruff]
target-version = "py312"
line-length = 125

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",
    "ISC001",
    "D10",
    "D212",
    "D203",
    "D404",
    "CPY001",
    "PLR6301",
    "PLR2004",
    "A005",
    "RUF029",
    "RUF036",
    "FBT003",
    "DTZ005",
]

[tool.ruff.lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 15

[tool.ruff.lint.pylint]
max-returns = 10
max-locals = 20

[tool.ruff.lint.isort]
split-on-trailing-comma = true
combine-as-imports = true

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.pyright]
useLibraryCodeForTypes = true
typeCheckingMode = "strict"
pythonVersion = "3.12"
enableExperimentalFeatures = true
reportIncompatibleMethodOverride = false
reportCallInDefaultInitializer = true
reportImplicitStringConcatenation = true
reportMissingSuperCall = true
reportPropertyTypeMismatch = true
reportShadowedImports = true
reportUnnecessaryTypeIgnoreComment = true
